/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package checkers;

import checkers.bot.fenandezprudencio.FernandezPrudencioBot;
import checkers.bot.gray.GrayRandomBot;

import java.util.Optional;

public class App {

    public static void main(String[] args) {
        CheckersBoard game = CheckersBoard.initBoard();
        CheckersPlayer player1 = new KeyboardPlayer();
        CheckersPlayer grayRandomBot = new GrayRandomBot();
        CheckersPlayer fernandezPrudencioBot = new FernandezPrudencioBot();
//        Optional<CheckersPlayer> loser = game.play(grayRandomBot, fernandezPrudencioBot);
        Optional<CheckersPlayer> loser = game.play(fernandezPrudencioBot, grayRandomBot);
        loser.ifPresent(
                checkersPlayer -> System.out.println("LOSER! " + checkersPlayer.getClass().getName()));
    }
}